# Generated by Django 3.2.7 on 2021-11-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211124_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='type',
            field=models.CharField(choices=[('Farmer', 'farm'), ('Investor', 'invest')], default='farm', max_length=30),
        ),
    ]
